## Numpy

In [44]:
import numpy as np

1. Создайте вектор состоящий из чисел от 0 до 11 включительно. 

In [45]:
Matrix = np.arange(0, 12)

2. Измените размерность вектора и превратите его в матрицу 3 х 4

In [46]:
Matrix = Matrix.reshape((3,4))
Matrix

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

3. Найдите произведение полученной матрицы и вектора [2, 3, 5, 6]

In [47]:
v = np.array([2,3,5,6])
op = Matrix.dot(v)
op

array([ 31,  95, 159])

4. Из матрицы из пункта 2 сделайте квадратную матрицу состоящую из строк с индексами 0, 1, 3

In [48]:
Matrix = Matrix.T[[0, 1, 3]].T
Matrix

array([[ 0,  1,  3],
       [ 4,  5,  7],
       [ 8,  9, 11]])

5. Найдите обратную матрицу к полученной в пункте 4.

In [49]:
Matrix_inv = np.linalg.inv(Matrix)

LinAlgError: Singular matrix

6. Проверьте является ли она обратной?

In [50]:
Matrix.dot(Matrix_inv)

NameError: name 'Matrix_inv' is not defined

## Pandas

1. Загрузите данные из https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv в DataFrame. Воспользуйтесь одним из способов предложенных на занятии.

In [28]:
import pandas as pd
url = 'https://raw.githubusercontent.com/alexeygrigorev/mlbookcamp-code/master/chapter-02-car-price/data.csv'
df = pd.read_csv(url)

2. Выведите несколько первых строк таблицы. 

In [24]:
df.head(3)

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350

3. Отфильруйте машины по марке и оставьте только строки с автомобилями BMW. 

In [25]:
df2 = df[df['Make'] == 'BMW']

4. Найдите среднюю стоимость автомобиля BMW и выведите данное значение с точность до двух знаком после запятой.

In [26]:
print('Средняя стоимость автомобиля BMW:', round(df2.groupby('Make')['MSRP'].mean().iloc[0], 2))

Средняя стоимость автомобиля BMW: 61546.76


5. Определите каких автомобилей больше с ручной коробокой передач или автоматической?

In [27]:
print('С автоматической коробкой передач:', df[df['Transmission Type'] == 'AUTOMATIC'].shape[0])
print('С ручной коробкой передач:', df[df['Transmission Type'] == 'MANUAL'].shape[0])
print('Больше автомобилей с автоматической коробкой передач')

С автоматической коробкой передач: 8266
С ручной коробкой передач: 2935
Больше автомобилей с автоматической коробкой передач
